Feature/menu
Coveros-Archive/coveros-mobile-app pull request #18
Opened 2017-06-30 13:14 UTC by SadieRynestad96

Menu drawer

2017-06-30 13:29 UTC, rkenney525 commented
Go ahead and resolve the conflicts first - you may want to work with @yeeunmariakim on this

2017-07-03 18:11 UTC, rkenney525 requested changes

2017-07-03 18:11 UTC, rkenney525 commented on app/src/main/java/com/coveros/coverosmobileapp/blogpost/BlogPostsListActivity.java
> +    private String[] menuTitles = new String[]{"Website","Blog","Bookmarks"};
make this final and static

2017-07-03 18:11 UTC, rkenney525 commented on app/src/main/java/com/coveros/coverosmobileapp/blogpost/BlogPostsListActivity.java
> +                    Intent a = new Intent(getApplicationContext(), MainActivity.class);
rewrite as `startActivity(new Intent(getApplicationContext(), MainActivity.class));`

use the same style for the one below

2017-07-03 18:11 UTC, rkenney525 commented on app/src/main/java/com/coveros/coverosmobileapp/blogpost/BlogPostsListActivity.java
> +            switch(position) {
Since there are only two cases just use an if-elseif statement

2017-07-03 18:11 UTC, rkenney525 commented on app/src/main/java/com/coveros/coverosmobileapp/blogpost/BlogPostsListActivity.java
> +        public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
Add Override annotation

2017-07-03 18:11 UTC, rkenney525 commented on app/src/main/java/com/coveros/coverosmobileapp/website/MainActivity.java
> +    private String[] menuTitles = new String[]{"Website","Blog","Bookmarks"};
See above comments, apply to this class as well

2017-07-03 18:50 UTC, rkenney525 approved these changes

2017-07-03 18:50 UTC, merged

2017-07-03 19:43 UTC, brhicks0414 reviewed
Looks good. Two small comments

2017-07-03 19:43 UTC, brhicks0414 commented on app/src/main/java/com/coveros/coverosmobileapp/blogpost/BlogPostsListActivity.java
> +    private static final String[] menuTitles = new String[]{"Website", "Blog", "Bookmarks"};
A general style suggestion for constants is to name them using all caps and underscores (i.e. MENU_TITLES)

2017-07-03 19:43 UTC, brhicks0414 commented on app/src/main/java/com/coveros/coverosmobileapp/website/MainActivity.java
> +    private static final String[] menuTitles = new String[]{"Website","Blog","Bookmarks"};
This is exactly the same list of menu titles is defined here and in BlogPostListActivities.java. If that is not a coincidence (and I'm guessing it isn't) then they should be defined in one place. Also, the previous suggestion regarding capitalization of constant names applies here as well.